version: '3'

services:
  db:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./data/mongodb:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=lappis
      - MONGO_INITDB_ROOT_PASSWORD=lappis
      - MONGO_INITDB_DATABASE=metabase
    networks:
      - stack

  metabase:
    image: metabase/metabase
    build: metabase/
    ports:
      - "3000:3000"
    environment:
      # - MB_DB_TYPE=mongodb
      # - MB_DB_DBNAME=metabase
      # - MB_DB_PORT=27017
      # - MB_DB_USER=metabase
      # - MB_DB_PASS=metabase
      # - MB_DB_HOST=db
      - MB_DB_FILE=/metabase-data/metabase.db
      # - MB_EMOJI_IN_LOGS=true
    volumes:
      - ./data/metabase:/metabase-data
    networks:
      - stack
    depends_on:
      - db

  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/usr/src/app/src
    working_dir: /usr/src/app
    command: python main.py
    networks:
      - stack
    depends_on:
      - metabase

networks:
  stack:
    driver: bridge
