name: Python CI

on:
  push:
    branches:
      - master
  pull_request:
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout no repositório
      uses: actions/checkout@v2

    - name: Setup Python 
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Instalar dependências
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Testes
      run: |
        python -m unittest discover -s tests

    - name: Documentação
      run: |
        pip install sphinx
        sphinx-build -b html source _build/html
        echo 'Documentation built.'

  #deploy:
  #  needs: build
  #  runs-on: ubuntu-latest

   # steps:
    #- name: Deploy para o https://pypi.orghttps://pypi.org